services:
  sankey-be:
    build:
      context: backend
      dockerfile: Dockerfile 
    env_file:
      - .env
    ports:
      - "${HOST_API_PORT:-4100}:4100"
    restart: unless-stopped
  sankey-fe:
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${HOST_APP_PORT:-3000}:3000"
    restart: unless-stopped